"""add competitors table

Revision ID: 1534b625d78e
Revises: c1783615d7b6
Create Date: 2026-07-28 21:34:20.165877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1534b625d78e'
down_revision: Union[str, None] = 'c1783615d7b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('serves_ice', sa.Boolean(), nullable=False),
    sa.Column('serves_water', sa.Boolean(), nullable=False),
    sa.Column('machine_type', sa.String(length=100), nullable=True),
    sa.Column('machine_size', sa.String(length=100), nullable=True),
    sa.Column('is_inside', sa.Boolean(), nullable=True),
    sa.Column('ice_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('water_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_notes', sa.String(length=500), nullable=True),
    sa.Column('estimated_market_share', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('last_observed_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_city_id'), 'competitors', ['city_id'], unique=False)
    op.create_index(op.f('ix_competitors_county_id'), 'competitors', ['county_id'], unique=False)
    op.create_index(op.f('ix_competitors_latitude'), 'competitors', ['latitude'], unique=False)
    op.create_index(op.f('ix_competitors_longitude'), 'competitors', ['longitude'], unique=False)
    op.create_index(op.f('ix_competitors_state_id'), 'competitors', ['state_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitors_state_id'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_longitude'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_latitude'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_county_id'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_city_id'), table_name='competitors')
    op.drop_table('competitors')
    # ### end Alembic commands ###
