"""add_photos_table

Revision ID: 77230dc23526
Revises: fd9926cf0add
Create Date: 2026-07-30 00:27:24.722930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77230dc23526'
down_revision: Union[str, None] = 'fd9926cf0add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_entity_id'), 'photos', ['entity_id'], unique=False)
    op.create_index(op.f('ix_photos_entity_type'), 'photos', ['entity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_entity_type'), table_name='photos')
    op.drop_index(op.f('ix_photos_entity_id'), table_name='photos')
    op.drop_table('photos')
    # ### end Alembic commands ###
