"""add_refresh_runs

Revision ID: 8ca73b6ba9dd
Revises: dc9a711ae96d
Create Date: 2026-07-30 21:35:00.642543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca73b6ba9dd'
down_revision: Union[str, None] = 'dc9a711ae96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('locations_reviewed', sa.Integer(), nullable=False),
    sa.Column('changes_queued', sa.Integer(), nullable=False),
    sa.Column('providers_used', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_runs')
    # ### end Alembic commands ###
