"""add validation queue and org review setting

Revision ID: b200f484556a
Revises: c7a2fb776f7c
Create Date: 2026-07-29 12:23:02.121030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b200f484556a'
down_revision: Union[str, None] = 'c7a2fb776f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('proposed_changes', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_queue_entity_id'), 'validation_queue', ['entity_id'], unique=False)
    op.create_index(op.f('ix_validation_queue_entity_type'), 'validation_queue', ['entity_type'], unique=False)
    op.create_index(op.f('ix_validation_queue_status'), 'validation_queue', ['status'], unique=False)
    op.create_index(op.f('ix_validation_queue_submitted_by'), 'validation_queue', ['submitted_by'], unique=False)
    op.add_column('organizations', sa.Column('require_review_for_submissions', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'require_review_for_submissions')
    op.drop_index(op.f('ix_validation_queue_submitted_by'), table_name='validation_queue')
    op.drop_index(op.f('ix_validation_queue_status'), table_name='validation_queue')
    op.drop_index(op.f('ix_validation_queue_entity_type'), table_name='validation_queue')
    op.drop_index(op.f('ix_validation_queue_entity_id'), table_name='validation_queue')
    op.drop_table('validation_queue')
    # ### end Alembic commands ###
