"""Location prospecting fields, call notes, update log

Revision ID: c1783615d7b6
Revises: 0001
Create Date: 2026-07-28 20:30:08.119294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1783615d7b6'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('field_name', sa.String(length=150), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('change_source', sa.String(length=30), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_update_log_changed_at'), 'update_log', ['changed_at'], unique=False)
    op.create_index(op.f('ix_update_log_entity_id'), 'update_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_update_log_entity_type'), 'update_log', ['entity_type'], unique=False)
    op.create_table('location_call_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('note_text', sa.String(length=2000), nullable=False),
    sa.Column('call_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_call_notes_follow_up_at'), 'location_call_notes', ['follow_up_at'], unique=False)
    op.create_index(op.f('ix_location_call_notes_location_id'), 'location_call_notes', ['location_id'], unique=False)
    op.add_column('locations', sa.Column('property_owner_name', sa.String(length=255), nullable=True))
    op.add_column('locations', sa.Column('property_owner_phone', sa.String(length=30), nullable=True))
    op.add_column('locations', sa.Column('property_management_company', sa.String(length=255), nullable=True))
    op.add_column('locations', sa.Column('property_management_contact_name', sa.String(length=255), nullable=True))
    op.add_column('locations', sa.Column('property_management_contact_phone', sa.String(length=30), nullable=True))
    op.add_column('locations', sa.Column('primary_contact_name', sa.String(length=255), nullable=True))
    op.add_column('locations', sa.Column('primary_contact_phone', sa.String(length=30), nullable=True))
    op.add_column('locations', sa.Column('expected_unit_size', sa.String(length=100), nullable=True))
    op.add_column('locations', sa.Column('power_connection_location', sa.String(length=500), nullable=True))
    op.add_column('locations', sa.Column('power_company', sa.String(length=255), nullable=True))
    op.add_column('locations', sa.Column('power_voltage', sa.String(length=30), nullable=True))
    op.add_column('locations', sa.Column('water_connection_location', sa.String(length=500), nullable=True))
    op.add_column('locations', sa.Column('water_company', sa.String(length=255), nullable=True))
    op.add_column('locations', sa.Column('sewer_connection_availability', sa.String(length=30), nullable=True))
    op.add_column('locations', sa.Column('sewer_connection_location', sa.String(length=500), nullable=True))
    op.add_column('locations', sa.Column('pricing_estimate_monthly', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('locations', sa.Column('pricing_estimate_notes', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'pricing_estimate_notes')
    op.drop_column('locations', 'pricing_estimate_monthly')
    op.drop_column('locations', 'sewer_connection_location')
    op.drop_column('locations', 'sewer_connection_availability')
    op.drop_column('locations', 'water_company')
    op.drop_column('locations', 'water_connection_location')
    op.drop_column('locations', 'power_voltage')
    op.drop_column('locations', 'power_company')
    op.drop_column('locations', 'power_connection_location')
    op.drop_column('locations', 'expected_unit_size')
    op.drop_column('locations', 'primary_contact_phone')
    op.drop_column('locations', 'primary_contact_name')
    op.drop_column('locations', 'property_management_contact_phone')
    op.drop_column('locations', 'property_management_contact_name')
    op.drop_column('locations', 'property_management_company')
    op.drop_column('locations', 'property_owner_phone')
    op.drop_column('locations', 'property_owner_name')
    op.drop_index(op.f('ix_location_call_notes_location_id'), table_name='location_call_notes')
    op.drop_index(op.f('ix_location_call_notes_follow_up_at'), table_name='location_call_notes')
    op.drop_table('location_call_notes')
    op.drop_index(op.f('ix_update_log_entity_type'), table_name='update_log')
    op.drop_index(op.f('ix_update_log_entity_id'), table_name='update_log')
    op.drop_index(op.f('ix_update_log_changed_at'), table_name='update_log')
    op.drop_table('update_log')
    # ### end Alembic commands ###
