"""add competitor contact and follow-up fields

Revision ID: c7a2fb776f7c
Revises: 1534b625d78e
Create Date: 2026-07-28 23:42:44.896433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a2fb776f7c'
down_revision: Union[str, None] = '1534b625d78e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitors', sa.Column('brand', sa.String(length=100), nullable=True))
    op.add_column('competitors', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('competitors', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('competitors', sa.Column('contact_name', sa.String(length=255), nullable=True))
    op.add_column('competitors', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('competitors', sa.Column('follow_up_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitors', 'follow_up_at')
    op.drop_column('competitors', 'contact_email')
    op.drop_column('competitors', 'contact_name')
    op.drop_column('competitors', 'phone')
    op.drop_column('competitors', 'website')
    op.drop_column('competitors', 'brand')
    # ### end Alembic commands ###
