"""add_location_website_and_primary_contact_email

Revision ID: fd9926cf0add
Revises: b200f484556a
Create Date: 2026-07-29 15:49:31.517706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9926cf0add'
down_revision: Union[str, None] = 'b200f484556a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('primary_contact_email', sa.String(length=255), nullable=True))
    op.add_column('locations', sa.Column('website', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'website')
    op.drop_column('locations', 'primary_contact_email')
    # ### end Alembic commands ###
